# This CI workflow can be triggered by PR creation or code push in PR, or manually using workflow dispatch.

name: CI workflow for installing terraform using terraform-install-template

on:
  workflow_dispatch:
  pull_request:
    branches: [ main,master ]

jobs:

  setup-environment:
    uses: karunakaranpalanichamy/reusable-workflows-modules/.github/workflows/terraform-install.yml@main
    with:
      terraform-version: 1.4.0
 
  deploy_dev_stage:
    uses: karunakaranpalanichamy/higher-environment-jobs-module/.github/workflows/infrastructure_workflow.yml@main

  run_downstream_jobs:
    uses: karunakaranpalanichamy/higher-environment-jobs-module/.github/workflows/higher-env-jobs-template.yml@main
